site:
  title: technicallyawriter
  url: https://technicallyawriter.org
  start_page: technicallyawriter::index.adoc
content:
  sources:
    - url: https://github.com/technicallyawriter/portfolio-docs.git
      branches: [main, "feature/*"]
ui:
  bundle:
    url: https://github.com/technicallyawriter/portfolio-ui/raw/main/build/ui-bundle.zip
    snapshot: true
